GhibliBackground:
  motion_module:
    - "models/Motion_Module/mm_sd_v14.ckpt"
    - "models/Motion_Module/mm_sd_v15.ckpt"

  dreambooth_path: "models/DreamBooth_LoRA/CounterfeitV30_30.safetensors"
  lora_model_path: "models/DreamBooth_LoRA/lora_Ghibli_n3.safetensors"
  lora_alpha: 1.0

  seed:           [-1]
  steps:          25
  guidance_scale: 7.5

  prompt:
    - "High quality photo of spring apricote trees,  out of the Wrold valley,  perfect  Apricot trees rows ,(extremely detailed CG unity 8k wallpaper), the most beautiful artwork in the world, Studio Ghibli"

  n_prompt:
    - "blur, low quality, churches, european architecture , naked, nude, distorted face, deformed face, bad anatomy"
