GhibliBackground:
  motion_module:
    - "models/Motion_Module/mm_sd_v14.ckpt"
    - "models/Motion_Module/mm_sd_v15.ckpt"

  dreambooth_path: "models/DreamBooth_LoRA/CounterfeitV30_30.safetensors"
  lora_model_path: "models/DreamBooth_LoRA/lora_Ghibli_n3.safetensors"
  lora_alpha: 1.0

  seed:           [-1]
  steps:          25
  guidance_scale: 7.5

  prompt:
    - "A  close-up photo of an wise old man sitting in an ancient chair, wearing a brown woollen dress, very graceful face, very cosy bed room with ancient furniture, winter cold, hobbits dress, intricate, face, highly detailed, 8 k,  art in the style of andreas rocha and studio ghibli"

  n_prompt:
    - "((Priest like dress)), (((Priest))),  ((blond)), (((wearing glasses))), blurred face, distorted faces, bad face, ugly, deformed nose, bad anatomy,  deformed boy , deformed arms, day light, more than two arms, multiple feet, LOW QUALITY"
